version: "3.9"

services:
  chanchito:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000" # Local port: container port
    links:
      - monguito
    volumes:
      - .:/home/app

  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - chanchito-data:/data/db

volumes:
  chanchito-data:



     